/** Bilingual copy for the AWiki settings section. */
/** Keys owned by the AWiki settings page. */
export type AwikiSettingsKey = 'nav' | 'intro' | 'tabAccount' | 'tabUsage' | 'tabAdvanced' | 'accountBalance' | 'billingMode' | 'billingStrict' | 'billingBypass' | 'billingBypassNotice' | 'modelStatus' | 'statusEnabled' | 'statusDisabled' | 'enableModels' | 'disableModels' | 'enablingModels' | 'disablingModels' | 'modelsEnabled' | 'modelsDisabled' | 'modelActionFailed' | 'insufficientBalanceTitle' | 'insufficientBalanceDescription' | 'modelAccessUnavailableTitle' | 'modelAccessUnavailable' | 'modelAccountLoading' | 'modelAccountUnavailable' | 'paymentsUnavailable' | 'rechargeAmount' | 'createRecharge' | 'creatingRecharge' | 'invalidRechargeAmount' | 'rechargeCreated' | 'rechargeFailed' | 'rechargePaid' | 'rechargeClosed' | 'rechargeStatusFailed' | 'paymentWindowFailed' | 'paymentQrAlt' | 'paymentQrHint' | 'paymentQrFailed' | 'pendingRechargeTitle' | 'pendingRechargeDescription' | 'pendingRechargeLimit' | 'continuePayment' | 'refreshPaymentStatus' | 'refreshingPaymentStatus' | 'rechargeOrderStatus' | 'orderPending' | 'orderPaid' | 'orderClosed' | 'usageLoading' | 'usageDescription' | 'usageDescriptionBypass' | 'reloadUsage' | 'usageEmpty' | 'usageTokens' | 'usageCalculated' | 'usageCharged' | 'usageNoPrice' | 'onboardingUseApiKey' | 'onboardingLater' | 'onboardingClose' | 'onboardingConnectTitle' | 'onboardingIdentityUnavailable' | 'onboardingModelTitle' | 'onboardingRegistrationDescription' | 'onboardingRestoreTitle' | 'onboardingRestoreDescription' | 'onboardingRestore' | 'onboardingEnableTitle' | 'onboardingBypassDescription' | 'onboardingStrictDescription' | 'onboardingInsufficientBalanceDescription' | 'onboardingPendingRechargeDescription' | 'goToRecharge' | 'identityLoading' | 'identitySignedOutRequired' | 'identityRegistrationRequired' | 'identityRestoring' | 'domainLabel' | 'domainDescription' | 'defaultValue' | 'save' | 'saving' | 'reset' | 'saved' | 'restartNotice' | 'identityNotice' | 'invalidDomain' | 'saveFailed' | 'loading' | 'unavailable' | 'readOnly' | 'dangerTitle' | 'dangerDescription' | 'clearLocalData' | 'clearDialogTitle' | 'clearDialogDescription' | 'clearScope' | 'clearRemoteNotice' | 'clearConfirmationLabel' | 'clearConfirmationPhrase' | 'clearConfirm' | 'clearing' | 'clearSucceeded' | 'clearFailed' | 'cancel';
/** Simplified Chinese dictionary. */
export declare const zh: Record<AwikiSettingsKey, string>;
/** English dictionary. */
export declare const en: Record<AwikiSettingsKey, string>;
declare module '@deepseek-ai/dsh-client-ui-slots' {
    interface LocaleNamespaceMap {
        'settings.awiki': AwikiSettingsKey;
    }
}
//# sourceMappingURL=settings-locales.d.ts.map