/** Bilingual copy for the AWiki identity and installation settings page. */
export type AwikiSettingsKey = 'nav' | 'intro' | 'tabsLabel' | 'basicTab' | 'devicesTab' | 'integrationTab' | 'devicesUnavailable' | 'devicesLoading' | 'domainLabel' | 'domainDescription' | 'defaultValue' | 'save' | 'saving' | 'reset' | 'saved' | 'restartNotice' | 'identityNotice' | 'invalidDomain' | 'saveFailed' | 'loading' | 'unavailable' | 'readOnly' | 'dangerTitle' | 'dangerDescription' | 'clearLocalData' | 'clearDialogTitle' | 'clearDialogDescription' | 'clearScope' | 'clearRemoteNotice' | 'clearConfirmationLabel' | 'clearConfirmationPhrase' | 'clearConfirm' | 'clearing' | 'clearSucceeded' | 'clearFailed' | 'cancel' | 'tenantTab' | 'localDataTab' | 'tenantLoading' | 'tenantUnavailable' | 'tenantDiagnostic' | 'tenantAdd' | 'tenantName' | 'tenantDomain' | 'tenantDomainHelp' | 'tenantCreate' | 'tenantCreated' | 'tenantOfficial' | 'tenantCustom' | 'tenantCurrent' | 'tenantSwitch' | 'tenantSwitching' | 'tenantSwitched' | 'tenantRenamed' | 'tenantArchive' | 'tenantArchived' | 'tenantChangeFailed' | 'updateTitle' | 'updateLoading' | 'updateUnavailable' | 'updateNoPolicy' | 'updateVersions' | 'updateRestricted' | 'updateRestart' | 'updateCheck' | 'updateCopy' | 'localDataNotice' | 'integrationTitle' | 'integrationDescription' | 'integrationLoading' | 'integrationGuide' | 'integrationName' | 'integrationNamePlaceholder' | 'integrationIntroduction' | 'integrationIntroductionPlaceholder' | 'integrationContactDeveloper' | 'integrationContactIntroduction' | 'integrationContactIntroductionPlaceholder' | 'integrationGroups' | 'integrationGroupIntroduction' | 'integrationGroupIntroductionPlaceholder' | 'integrationAddGroup' | 'integrationNoOwnedGroups' | 'integrationGroupsUnavailable' | 'integrationRemove' | 'integrationCopy' | 'integrationCreate' | 'integrationRotate' | 'integrationRotateConfirm' | 'integrationClose' | 'integrationCloseConfirm' | 'integrationClosed' | 'integrationClosedDescription' | 'integrationReopen';
export declare const zh: Record<AwikiSettingsKey, string>;
export declare const en: Record<AwikiSettingsKey, string>;
declare module '@deepseek-ai/dsh-client-ui-slots' {
    interface LocaleNamespaceMap {
        'settings.awiki': AwikiSettingsKey;
    }
}
//# sourceMappingURL=settings-locales.d.ts.map