/** Bilingual copy for the Model Proxy settings and onboarding surfaces. */
/** Keys owned by the Model Proxy settings and onboarding surfaces. */
export type ModelProxySettingsKey = 'nav' | 'intro' | 'tabAccount' | 'tabUsage' | 'accountBalance' | 'billingMode' | 'billingStrict' | 'billingBypass' | 'billingBypassNotice' | 'modelStatus' | 'modelSourceNotice' | 'statusEnabled' | 'statusDisabled' | 'enableModels' | 'disableModels' | 'enablingModels' | 'disablingModels' | 'modelsEnabled' | 'modelsDisabled' | 'modelActionFailed' | 'insufficientBalanceTitle' | 'insufficientBalanceDescription' | 'modelAccessUnavailableTitle' | 'modelAccessUnavailable' | 'modelAccountLoading' | 'modelAccountUnavailable' | 'paymentsUnavailable' | 'rechargeComingSoonTitle' | 'rechargeComingSoonDescription' | 'rechargeComingSoonAcknowledge' | 'rechargeComingSoonClose' | 'rechargeAmount' | 'createRecharge' | 'creatingRecharge' | 'invalidRechargeAmount' | 'rechargeCreated' | 'rechargeFailed' | 'rechargePaid' | 'rechargeClosed' | 'rechargeStatusFailed' | 'paymentWindowFailed' | 'paymentQrAlt' | 'paymentQrHint' | 'paymentQrFailed' | 'pendingRechargeTitle' | 'pendingRechargeDescription' | 'pendingRechargeLimit' | 'continuePayment' | 'changeRechargeAmount' | 'cancelRechargeDialogTitle' | 'cancelRechargeDialogDescription' | 'cancelRechargeWarning' | 'confirmCancelRecharge' | 'cancellingRecharge' | 'rechargeCancelled' | 'rechargeCancelFailed' | 'refreshPaymentStatus' | 'refreshingPaymentStatus' | 'rechargeOrderStatus' | 'orderPending' | 'orderPaid' | 'orderClosed' | 'usageLoading' | 'usageDescription' | 'usageDescriptionBypass' | 'reloadUsage' | 'usageEmpty' | 'usageTokens' | 'usageCalculated' | 'usageCharged' | 'usageNoPrice' | 'onboardingUseApiKey' | 'onboardingLater' | 'onboardingClose' | 'onboardingConnectTitle' | 'onboardingIdentityUnavailable' | 'onboardingModelTitle' | 'onboardingRegistrationDescription' | 'onboardingRestoreTitle' | 'onboardingRestoreDescription' | 'onboardingRecoveryRequiredTitle' | 'onboardingRecoveryRequiredDescription' | 'onboardingRestore' | 'onboardingEnableTitle' | 'onboardingBypassDescription' | 'onboardingStrictDescription' | 'onboardingInsufficientBalanceDescription' | 'onboardingPendingRechargeDescription' | 'goToRecharge' | 'identityLoading' | 'identitySignedOutRequired' | 'identityRegistrationRequired' | 'identityRecoveryRequired' | 'identityRestoring' | 'contactDeveloper' | 'contactPluginMissingTitle' | 'contactPluginMissingDescription' | 'contactPluginCopyCommand' | 'contactPluginCopied' | 'contactPluginMissingAcknowledge' | 'contactPluginMissingClose' | 'cancel';
/** Simplified Chinese dictionary. */
export declare const zh: Record<ModelProxySettingsKey, string>;
/** English dictionary. */
export declare const en: Record<ModelProxySettingsKey, string>;
declare module '@deepseek-ai/dsh-client-ui-slots' {
    interface LocaleNamespaceMap {
        'settings.awiki-model-proxy': ModelProxySettingsKey;
    }
}
//# sourceMappingURL=settings-locales.d.ts.map