/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_awiki_awiki_clearLocalData_parameter_0$schema = z.object({
  'confirmation': z.string().readonly(),
})
const dsh_awiki_awiki_clearLocalData_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'cleared': z.boolean().readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_downloadAttachment_parameter_0$schema = z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()).readonly(),
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
})
const dsh_awiki_awiki_downloadAttachment_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'attachment': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'size': z.number().readonly(),
  'sha256': z.string().readonly(),
}).readonly(),
  'bytesBase64': z.string().readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_getConfig_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'pollIntervalMs': z.number().readonly(),
  'attachmentMaxBytes': z.number().readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_getHistory_parameter_0$schema = z.object({
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'cursor': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
})
const dsh_awiki_awiki_getHistory_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationKind': z.union([z.literal("direct"), z.literal("group")]).readonly(),
  'senderDid': z.intersection(z.string(), z.unknown()).readonly(),
  'senderHandle': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'senderDisplayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sentAt': z.number().readonly(),
  'outgoing': z.boolean().readonly(),
  'content': z.union([z.object({
  'kind': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'kind': z.literal("attachment").readonly(),
  'attachment': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'size': z.number().readonly(),
  'sha256': z.string().readonly(),
}).readonly(),
  'caption': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly(),
})).readonly(),
  'nextCursor': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'hasMore': z.boolean().readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_getIdentity_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.literal(null), z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'registeredAt': z.number().readonly(),
})]).readonly(),
})])
const dsh_awiki_awiki_listConversations_parameter_0$schema = z.union([z.undefined(), z.object({
  'cursor': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
})])
const dsh_awiki_awiki_listConversations_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.union([z.object({
  'kind': z.literal("direct").readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'peerDid': z.intersection(z.string(), z.unknown()).readonly(),
  'peerHandle': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'displayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'title': z.string().readonly(),
  'unreadCount': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastMessageAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastMessagePreview': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'kind': z.literal("group").readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'groupDid': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'unreadCount': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastMessageAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastMessagePreview': z.union([z.undefined(), z.string()]).readonly().optional(),
})])).readonly(),
  'nextCursor': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'hasMore': z.boolean().readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_markConversationRead_parameter_0$schema = z.object({
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
})
const dsh_awiki_awiki_markConversationRead_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.number().readonly(),
})])
const dsh_awiki_awiki_registerIdentity_parameter_0$schema = z.object({
  'handle': z.string().readonly(),
  'phone': z.string().readonly(),
  'otp': z.string().readonly(),
})
const dsh_awiki_awiki_registerIdentity_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'registeredAt': z.number().readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_resolvePeer_parameter_0$schema = z.object({
  'peer': z.string().readonly(),
})
const dsh_awiki_awiki_resolvePeer_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'handle': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'displayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_sendAttachment_parameter_0$schema = z.object({
  'target': z.union([z.object({
  'kind': z.literal("direct").readonly(),
  'peer': z.string().readonly(),
}), z.object({
  'kind': z.literal("group").readonly(),
  'group': z.string().readonly(),
})]).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'bytesBase64': z.string().readonly(),
  'caption': z.union([z.undefined(), z.string()]).readonly().optional(),
  'idempotencyKey': z.string().readonly(),
})
const dsh_awiki_awiki_sendAttachment_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationKind': z.union([z.literal("direct"), z.literal("group")]).readonly(),
  'senderDid': z.intersection(z.string(), z.unknown()).readonly(),
  'senderHandle': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'senderDisplayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sentAt': z.number().readonly(),
  'outgoing': z.boolean().readonly(),
  'content': z.union([z.object({
  'kind': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'kind': z.literal("attachment").readonly(),
  'attachment': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'size': z.number().readonly(),
  'sha256': z.string().readonly(),
}).readonly(),
  'caption': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_sendRegistrationOtp_parameter_0$schema = z.object({
  'handle': z.string().readonly(),
  'phone': z.string().readonly(),
})
const dsh_awiki_awiki_sendRegistrationOtp_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'retryAfterSeconds': z.number().readonly(),
  'retryAt': z.string().readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_sendText_parameter_0$schema = z.object({
  'target': z.union([z.object({
  'kind': z.literal("direct").readonly(),
  'peer': z.string().readonly(),
}), z.object({
  'kind': z.literal("group").readonly(),
  'group': z.string().readonly(),
})]).readonly(),
  'text': z.string().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const dsh_awiki_awiki_sendText_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationKind': z.union([z.literal("direct"), z.literal("group")]).readonly(),
  'senderDid': z.intersection(z.string(), z.unknown()).readonly(),
  'senderHandle': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'senderDisplayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sentAt': z.number().readonly(),
  'outgoing': z.boolean().readonly(),
  'content': z.union([z.object({
  'kind': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'kind': z.literal("attachment").readonly(),
  'attachment': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'size': z.number().readonly(),
  'sha256': z.string().readonly(),
}).readonly(),
  'caption': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_summarizeConversation_parameter_0$schema = z.object({
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'unreadCountAtOpen': z.union([z.undefined(), z.number()]).readonly().optional(),
})
const dsh_awiki_awiki_summarizeConversation_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'range': z.object({
  'kind': z.union([z.literal("unread"), z.literal("recent")]).readonly(),
  'messageCount': z.number().readonly(),
  'firstMessageId': z.intersection(z.string(), z.unknown()).readonly(),
  'lastMessageId': z.intersection(z.string(), z.unknown()).readonly(),
  'startedAt': z.number().readonly(),
  'endedAt': z.number().readonly(),
  'truncated': z.boolean().readonly(),
}).readonly(),
  'highlights': z.array(z.string()).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'todos': z.array(z.object({
  'text': z.string().readonly(),
  'owner': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
}).readonly(),
})])
const dsh_awiki_awiki_updateDisplayName_parameter_0$schema = z.object({
  'displayName': z.string().readonly(),
})
const dsh_awiki_awiki_updateDisplayName_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'registeredAt': z.number().readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: 'dsh-awiki',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-awiki#awiki/clearLocalData',
      service: 'awiki',
      namespace: 'awiki',
      method: 'clearLocalData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiClearLocalDataRequest',
            schema: dsh_awiki_awiki_clearLocalData_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_clearLocalData_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":736,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/downloadAttachment',
      service: 'awiki',
      namespace: 'awiki',
      method: 'downloadAttachment',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiDownloadAttachmentRequest',
            schema: dsh_awiki_awiki_downloadAttachment_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_downloadAttachment_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":717,"column":9},
    },
    {
      id: 'dsh-awiki#awiki/getConfig',
      service: 'awiki',
      namespace: 'awiki',
      method: 'getConfig',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_getConfig_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":518,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/getHistory',
      service: 'awiki',
      namespace: 'awiki',
      method: 'getHistory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiHistoryRequest',
            schema: dsh_awiki_awiki_getHistory_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_getHistory_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":593,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/getIdentity',
      service: 'awiki',
      namespace: 'awiki',
      method: 'getIdentity',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_getIdentity_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":533,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/listConversations',
      service: 'awiki',
      namespace: 'awiki',
      method: 'listConversations',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiPageRequest',
            schema: dsh_awiki_awiki_listConversations_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_listConversations_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":583,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/markConversationRead',
      service: 'awiki',
      namespace: 'awiki',
      method: 'markConversationRead',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiMarkConversationReadRequest',
            schema: dsh_awiki_awiki_markConversationRead_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_markConversationRead_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":676,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/registerIdentity',
      service: 'awiki',
      namespace: 'awiki',
      method: 'registerIdentity',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiRegistrationRequest',
            schema: dsh_awiki_awiki_registerIdentity_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_registerIdentity_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":553,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/resolvePeer',
      service: 'awiki',
      namespace: 'awiki',
      method: 'resolvePeer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiResolvePeerRequest',
            schema: dsh_awiki_awiki_resolvePeer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_resolvePeer_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":573,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/sendAttachment',
      service: 'awiki',
      namespace: 'awiki',
      method: 'sendAttachment',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiSendAttachmentRequest',
            schema: dsh_awiki_awiki_sendAttachment_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_sendAttachment_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":696,"column":9},
    },
    {
      id: 'dsh-awiki#awiki/sendRegistrationOtp',
      service: 'awiki',
      namespace: 'awiki',
      method: 'sendRegistrationOtp',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiRegistrationOtpRequest',
            schema: dsh_awiki_awiki_sendRegistrationOtp_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_sendRegistrationOtp_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":543,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/sendText',
      service: 'awiki',
      namespace: 'awiki',
      method: 'sendText',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiSendTextRequest',
            schema: dsh_awiki_awiki_sendText_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_sendText_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":686,"column":3},
    },
    {
      id: 'dsh-awiki#awiki/summarizeConversation',
      service: 'awiki',
      namespace: 'awiki',
      method: 'summarizeConversation',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiSummarizeConversationRequest',
            schema: dsh_awiki_awiki_summarizeConversation_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_summarizeConversation_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":603,"column":9},
    },
    {
      id: 'dsh-awiki#awiki/updateDisplayName',
      service: 'awiki',
      namespace: 'awiki',
      method: 'updateDisplayName',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-awiki/types#AwikiUpdateDisplayNameRequest',
            schema: dsh_awiki_awiki_updateDisplayName_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-awiki/types#AwikiResult',
        schema: dsh_awiki_awiki_updateDisplayName_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-awiki/src/index.ts","line":563,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Deployment-wide AWiki service over one replaceable TypeScript client provider.",
        "summary": "Deployment-wide AWiki service over one replaceable TypeScript client provider.",
        "tags": [],
        "jsDoc": "/** Deployment-wide AWiki service over one replaceable TypeScript client provider. */",
        "key": "awiki",
        "exportName": "AwikiService",
        "members": [
          {
            "kind": "method",
            "name": "registerClientFactory",
            "signature": "registerClientFactory(factory: AwikiClientFactory): () => Promise<void>",
            "summary": "Register the deployment's sole client factory.",
            "jsDoc": "/**\n * Register the deployment's sole client factory. The caller must return the\n * resulting disposer from its own `ctx.effect`; disposal clears the slot\n * before awaiting the client's quiescence and is idempotent.\n * @param factory - synchronous factory for one owned high-level client.\n * @returns asynchronous disposer for the exact registered client.\n */"
          },
          {
            "kind": "method",
            "name": "registerSummaryProvider",
            "signature": "registerSummaryProvider(provider: AwikiSummaryProvider): () => void",
            "summary": "Register one replaceable conversation-summary provider for this deployment.",
            "jsDoc": "/** Register one replaceable conversation-summary provider for this deployment. */"
          },
          {
            "kind": "method",
            "name": "getConfig",
            "signature": "@Remote getConfig(): Promise<AwikiResult<AwikiRuntimeConfig>>",
            "summary": "Read settings needed by the browser presentation.",
            "jsDoc": "/**\n * Read settings needed by the browser presentation.\n * @returns Browser-safe polling configuration without SDK endpoints or state paths.\n */"
          },
          {
            "kind": "method",
            "name": "getIdentity",
            "signature": "@Remote getIdentity(): Promise<AwikiResult<AwikiIdentity | null>>",
            "summary": "Read the deployment's identity status.",
            "jsDoc": "/**\n * Read the deployment's identity status.\n * @returns The public deployment identity or `null`.\n */"
          },
          {
            "kind": "method",
            "name": "sendRegistrationOtp",
            "signature": "@Remote sendRegistrationOtp(request: AwikiRegistrationOtpRequest): Promise<AwikiResult<AwikiRegistrationOtpResult>>",
            "summary": "Send one Legacy registration verification code.",
            "jsDoc": "/**\n * Send one Legacy registration verification code.\n * @param request - Handle and phone used for the registration challenge.\n * @returns Public retry timing or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "registerIdentity",
            "signature": "@Remote registerIdentity(request: AwikiRegistrationRequest): Promise<AwikiResult<AwikiIdentity>>",
            "summary": "Register and persist the deployment's only AWiki identity.",
            "jsDoc": "/**\n * Register and persist the deployment's only AWiki identity.\n * @param request - Handle, phone, and verification code for registration.\n * @returns The new public identity or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "updateDisplayName",
            "signature": "@Remote updateDisplayName(request: AwikiUpdateDisplayNameRequest): Promise<AwikiResult<AwikiIdentity>>",
            "summary": "Update the deployment identity's public WNS display name.",
            "jsDoc": "/**\n * Update the deployment identity's public WNS display name.\n * @param request - replacement display name selected by the user.\n * @returns The updated public identity or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "resolvePeer",
            "signature": "@Remote resolvePeer(request: AwikiResolvePeerRequest): Promise<AwikiResult<AwikiResolvedPeer>>",
            "summary": "Resolve one Handle or DID before the browser opens a direct chat.",
            "jsDoc": "/**\n * Resolve one Handle or DID before the browser opens a direct chat.\n * @param request - typed Handle or DID.\n * @returns The public peer and conversation id, or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "listConversations",
            "signature": "@Remote listConversations(request?: AwikiPageRequest): Promise<AwikiResult<AwikiPage<AwikiConversation>>>",
            "summary": "List direct and existing group conversations.",
            "jsDoc": "/**\n * List direct and existing group conversations.\n * @param request - Optional opaque cursor and page limit.\n * @returns One page of direct and existing group conversations.\n */"
          },
          {
            "kind": "method",
            "name": "getHistory",
            "signature": "@Remote getHistory(request: AwikiHistoryRequest): Promise<AwikiResult<AwikiPage<AwikiMessage>>>",
            "summary": "Read one direct or group conversation history page.",
            "jsDoc": "/**\n * Read one direct or group conversation history page.\n * @param request - Conversation id, optional cursor, and page limit.\n * @returns One chronological history page.\n */"
          },
          {
            "kind": "method",
            "name": "summarizeConversation",
            "signature": "@Remote async summarizeConversation( request: AwikiSummarizeConversationRequest, ): Promise<AwikiResult<AwikiConversationSummary>>",
            "summary": "Read real AWiki history, enforce range and byte caps, then invoke the configured model once.",
            "jsDoc": "/**\n * Read real AWiki history, enforce range and byte caps, then invoke the configured model once.\n * @param request - selected conversation and its unread snapshot at open time.\n * @returns a structured summary plus the exact summarized source range.\n */"
          },
          {
            "kind": "method",
            "name": "markConversationRead",
            "signature": "@Remote markConversationRead(request: AwikiMarkConversationReadRequest): Promise<AwikiResult<number>>",
            "summary": "Mark every currently unread inbox message in one conversation as read.",
            "jsDoc": "/**\n * Mark every currently unread inbox message in one conversation as read.\n * @param request - conversation whose current inbox entries should be acknowledged.\n * @returns Number of inbox entries acknowledged by the Message Service.\n */"
          },
          {
            "kind": "method",
            "name": "sendText",
            "signature": "@Remote sendText(request: AwikiSendTextRequest): Promise<AwikiResult<AwikiMessage>>",
            "summary": "Send one text message through the deployment identity.",
            "jsDoc": "/**\n * Send one text message through the deployment identity.\n * @param request - Target, text, and idempotency key.\n * @returns The accepted public message or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "sendAttachment",
            "signature": "@Remote async sendAttachment(request: AwikiSendAttachmentRequest): Promise<AwikiResult<AwikiMessage>>",
            "summary": "Upload and send one attachment after Host validation.",
            "jsDoc": "/**\n * Upload and send one attachment after Host validation.\n * @param request - Target, attachment metadata and Base64 bytes, caption, and idempotency key.\n * @returns The accepted attachment message or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "downloadAttachment",
            "signature": "@Remote async downloadAttachment(request: AwikiDownloadAttachmentRequest): Promise<AwikiResult<AwikiDownloadedAttachment>>",
            "summary": "Download and encode one provider-verified attachment.",
            "jsDoc": "/**\n * Download and encode one provider-verified attachment.\n * @param request - Containing message id and attachment id.\n * @returns Verified public metadata and canonical Base64 bytes, or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "clearLocalData",
            "signature": "@Remote clearLocalData(request: AwikiClearLocalDataRequest): Promise<AwikiResult<AwikiClearLocalDataResult>>",
            "summary": "Permanently remove the exact SDK-owned local state after an explicit browser acknowledgement.",
            "jsDoc": "/**\n * Permanently remove the exact SDK-owned local state after an explicit browser acknowledgement.\n * The remote AWiki account and Handle are not deleted.\n * @param request - exact destructive-action marker emitted only after the UI's second confirmation.\n * @returns Whether a persisted state file existed when the reset completed.\n */"
          }
        ],
        "types": [
          {
            "name": "AwikiAttachment",
            "declaration": "export interface AwikiAttachment {\n    readonly id: AwikiAttachmentId;\n    readonly fileName: string;\n    readonly mimeType: string;\n    readonly size: number;\n    readonly sha256: string;\n}"
          },
          {
            "name": "AwikiAttachmentContent",
            "declaration": "export interface AwikiAttachmentContent {\n    readonly kind: 'attachment';\n    readonly attachment: AwikiAttachment;\n    readonly caption?: string;\n}"
          },
          {
            "name": "AwikiAttachmentId",
            "declaration": "export type AwikiAttachmentId = Branded<'AwikiAttachmentId'>;"
          },
          {
            "name": "AwikiClearLocalDataRequest",
            "declaration": "export interface AwikiClearLocalDataRequest {\n    readonly confirmation: string;\n}"
          },
          {
            "name": "AwikiClearLocalDataResult",
            "declaration": "export interface AwikiClearLocalDataResult {\n    readonly cleared: boolean;\n}"
          },
          {
            "name": "AwikiClientFactory",
            "declaration": "export type AwikiClientFactory = (options: AwikiClientOptions) => AwikiSdkClient;"
          },
          {
            "name": "AwikiClientOptions",
            "declaration": "export interface AwikiClientOptions {\n    readonly userServiceUrl: string;\n    readonly userServiceDomain: string;\n    readonly messageServiceUrl: string;\n    readonly messageServicePublicUrl: string;\n    readonly messageServiceDid: string;\n    readonly allowedAttachmentOrigins: readonly string[];\n    readonly attachmentMaxBytes: number;\n    readonly allowInsecureLoopbackForTesting: boolean;\n    readonly statePath: string;\n}"
          },
          {
            "name": "AwikiConversation",
            "declaration": "export type AwikiConversation = AwikiDirectConversation | AwikiGroupConversation;"
          },
          {
            "name": "AwikiConversationId",
            "declaration": "export type AwikiConversationId = Branded<'AwikiConversationId'>;"
          },
          {
            "name": "AwikiConversationSummary",
            "declaration": "export interface AwikiConversationSummary {\n    readonly range: AwikiSummaryRange;\n    readonly highlights: readonly string[];\n    readonly conclusions: readonly string[];\n    readonly todos: readonly AwikiSummaryTodo[];\n}"
          },
          {
            "name": "AwikiCursor",
            "declaration": "export type AwikiCursor = Branded<'AwikiCursor'>;"
          },
          {
            "name": "AwikiDid",
            "declaration": "export type AwikiDid = Branded<'AwikiDid'>;"
          },
          {
            "name": "AwikiDirectConversation",
            "declaration": "export interface AwikiDirectConversation {\n    readonly kind: 'direct';\n    readonly id: AwikiConversationId;\n    readonly peerDid: AwikiDid;\n    readonly peerHandle?: AwikiHandle;\n    readonly displayName?: string;\n    readonly title: string;\n    readonly unreadCount?: number;\n    readonly lastMessageAt?: number;\n    readonly lastMessagePreview?: string;\n}"
          },
          {
            "name": "AwikiDirectTarget",
            "declaration": "export interface AwikiDirectTarget {\n    readonly kind: 'direct';\n    readonly peer: string;\n}"
          },
          {
            "name": "AwikiDownloadAttachmentRequest",
            "declaration": "export interface AwikiDownloadAttachmentRequest {\n    readonly attachmentId: AwikiAttachmentId;\n    readonly messageId: AwikiMessageId;\n}"
          },
          {
            "name": "AwikiDownloadedAttachment",
            "declaration": "export interface AwikiDownloadedAttachment {\n    readonly attachment: AwikiAttachment;\n    readonly bytesBase64: string;\n}"
          },
          {
            "name": "AwikiFailure",
            "declaration": "export interface AwikiFailure {\n    readonly code: AwikiFailureCode;\n    readonly message: string;\n}"
          },
          {
            "name": "AwikiFailureCode",
            "declaration": "export type AwikiFailureCode = 'not-registered' | 'already-registered' | 'invalid-request' | 'invalid-otp' | 'challenge-expired' | 'handle-unavailable' | 'not-found' | 'forbidden' | 'conflict' | 'rate-limited' | 'attachment-too-large' | 'summary-unavailable' | 'summary-timeout' | 'summary-cancelled' | 'summary-invalid-output' | 'summary-failed' | 'network' | 'remote';"
          },
          {
            "name": "AwikiGroupConversation",
            "declaration": "export interface AwikiGroupConversation {\n    readonly kind: 'group';\n    readonly id: AwikiConversationId;\n    readonly groupDid: AwikiDid;\n    readonly title: string;\n    readonly unreadCount?: number;\n    readonly lastMessageAt?: number;\n    readonly lastMessagePreview?: string;\n}"
          },
          {
            "name": "AwikiGroupTarget",
            "declaration": "export interface AwikiGroupTarget {\n    readonly kind: 'group';\n    readonly group: string;\n}"
          },
          {
            "name": "AwikiHandle",
            "declaration": "export type AwikiHandle = Branded<'AwikiHandle'>;"
          },
          {
            "name": "AwikiHistoryRequest",
            "declaration": "export interface AwikiHistoryRequest extends AwikiPageRequest {\n    readonly conversationId: AwikiConversationId;\n}"
          },
          {
            "name": "AwikiIdentity",
            "declaration": "export interface AwikiIdentity {\n    readonly handle: AwikiHandle;\n    readonly did: AwikiDid;\n    readonly displayName?: string;\n    readonly registeredAt: number;\n}"
          },
          {
            "name": "AwikiMarkConversationReadRequest",
            "declaration": "export interface AwikiMarkConversationReadRequest {\n    readonly conversationId: AwikiConversationId;\n}"
          },
          {
            "name": "AwikiMessage",
            "declaration": "export interface AwikiMessage {\n    readonly id: AwikiMessageId;\n    readonly conversationId: AwikiConversationId;\n    readonly conversationKind: AwikiConversation['kind'];\n    readonly senderDid: AwikiDid;\n    readonly senderHandle?: AwikiHandle;\n    readonly senderDisplayName?: string;\n    readonly sentAt: number;\n    readonly outgoing: boolean;\n    readonly content: AwikiMessageContent;\n}"
          },
          {
            "name": "AwikiMessageContent",
            "declaration": "export type AwikiMessageContent = AwikiTextContent | AwikiAttachmentContent;"
          },
          {
            "name": "AwikiMessageId",
            "declaration": "export type AwikiMessageId = Branded<'AwikiMessageId'>;"
          },
          {
            "name": "AwikiMessageTarget",
            "declaration": "export type AwikiMessageTarget = AwikiDirectTarget | AwikiGroupTarget;"
          },
          {
            "name": "AwikiPage",
            "declaration": "export interface AwikiPage<Item> {\n    readonly items: readonly Item[];\n    readonly nextCursor?: AwikiCursor;\n    readonly hasMore: boolean;\n}"
          },
          {
            "name": "AwikiPageRequest",
            "declaration": "export interface AwikiPageRequest {\n    readonly cursor?: AwikiCursor;\n    readonly limit?: number;\n}"
          },
          {
            "name": "AwikiRegistrationOtpRequest",
            "declaration": "export interface AwikiRegistrationOtpRequest {\n    readonly handle: string;\n    readonly phone: string;\n}"
          },
          {
            "name": "AwikiRegistrationOtpResult",
            "declaration": "export interface AwikiRegistrationOtpResult {\n    readonly retryAfterSeconds: number;\n    readonly retryAt: string;\n}"
          },
          {
            "name": "AwikiRegistrationRequest",
            "declaration": "export interface AwikiRegistrationRequest {\n    readonly handle: string;\n    readonly phone: string;\n    readonly otp: string;\n}"
          },
          {
            "name": "AwikiRejected",
            "declaration": "export interface AwikiRejected {\n    readonly ok: false;\n    readonly error: AwikiFailure;\n}"
          },
          {
            "name": "AwikiResolvedPeer",
            "declaration": "export interface AwikiResolvedPeer {\n    readonly did: AwikiDid;\n    readonly handle?: AwikiHandle;\n    readonly displayName?: string;\n    readonly conversationId: AwikiConversationId;\n}"
          },
          {
            "name": "AwikiResolvePeerRequest",
            "declaration": "export interface AwikiResolvePeerRequest {\n    readonly peer: string;\n}"
          },
          {
            "name": "AwikiResult",
            "declaration": "export type AwikiResult<Value> = AwikiSuccess<Value> | AwikiRejected;"
          },
          {
            "name": "AwikiRuntimeConfig",
            "declaration": "export interface AwikiRuntimeConfig {\n    readonly pollIntervalMs: number;\n    readonly attachmentMaxBytes: number;\n}"
          },
          {
            "name": "AwikiSdkAttachmentUpload",
            "declaration": "export interface AwikiSdkAttachmentUpload {\n    readonly fileName: string;\n    readonly mimeType: string;\n    readonly bytes: Uint8Array;\n}"
          },
          {
            "name": "AwikiSdkClient",
            "declaration": "export interface AwikiSdkClient {\n    getIdentity(): Promise<AwikiIdentity | null>;\n    sendRegistrationOtp(request: AwikiRegistrationOtpRequest): Promise<AwikiRegistrationOtpResult>;\n    registerIdentity(request: AwikiRegistrationRequest): Promise<AwikiIdentity>;\n    updateDisplayName(request: AwikiUpdateDisplayNameRequest): Promise<AwikiIdentity>;\n    resolvePeer(peer: string): Promise<AwikiResolvedPeer>;\n    listConversations(request?: AwikiPageRequest): Promise<AwikiPage<AwikiConversation>>;\n    getHistory(request: AwikiHistoryRequest): Promise<AwikiPage<AwikiMessage>>;\n    markConversationRead(conversationId: AwikiConversationId): Promise<number>;\n    sendText(request: AwikiSendTextRequest): Promise<AwikiMessage>;\n    sendAttachment(request: AwikiSdkSendAttachmentRequest): Promise<AwikiMessage>;\n    downloadAttachment(request: { readonly attachmentId: AwikiAttachmentId; readonly messageId: AwikiMessageId; }): Promise<AwikiSdkDownloadedAttachment>;\n    clearLocalData(): Promise<{ readonly cleared: boolean; }>;\n    dispose(): Promise<void>;\n}"
          },
          {
            "name": "AwikiSdkDownloadedAttachment",
            "declaration": "export interface AwikiSdkDownloadedAttachment {\n    readonly attachment: AwikiAttachment;\n    readonly bytes: Uint8Array;\n}"
          },
          {
            "name": "AwikiSdkSendAttachmentRequest",
            "declaration": "export interface AwikiSdkSendAttachmentRequest {\n    readonly target: AwikiMessageTarget;\n    readonly attachment: AwikiSdkAttachmentUpload;\n    readonly caption?: string;\n    readonly idempotencyKey: string;\n}"
          },
          {
            "name": "AwikiSendAttachmentRequest",
            "declaration": "export interface AwikiSendAttachmentRequest {\n    readonly target: AwikiMessageTarget;\n    readonly fileName: string;\n    readonly mimeType: string;\n    readonly bytesBase64: string;\n    readonly caption?: string;\n    readonly idempotencyKey: string;\n}"
          },
          {
            "name": "AwikiSendTextRequest",
            "declaration": "export interface AwikiSendTextRequest {\n    readonly target: AwikiMessageTarget;\n    readonly text: string;\n    readonly idempotencyKey: string;\n}"
          },
          {
            "name": "AwikiSuccess",
            "declaration": "export interface AwikiSuccess<Value> {\n    readonly ok: true;\n    readonly value: Value;\n}"
          },
          {
            "name": "AwikiSummarizeConversationRequest",
            "declaration": "export interface AwikiSummarizeConversationRequest {\n    readonly conversationId: AwikiConversationId;\n    readonly unreadCountAtOpen?: number;\n}"
          },
          {
            "name": "AwikiSummaryAttachmentMessage",
            "declaration": "export interface AwikiSummaryAttachmentMessage {\n    readonly id: AwikiMessageId;\n    readonly sender: string;\n    readonly outgoing: boolean;\n    readonly sentAt: string;\n    readonly content: { readonly kind: 'attachment'; readonly fileName: string; readonly mimeType: string; readonly size: number; readonly caption?: string; };\n}"
          },
          {
            "name": "AwikiSummaryProvider",
            "declaration": "export interface AwikiSummaryProvider {\n    summarize(request: AwikiSummaryProviderRequest): Promise<AwikiSummaryProviderResult>;\n}"
          },
          {
            "name": "AwikiSummaryProviderRequest",
            "declaration": "export interface AwikiSummaryProviderRequest {\n    readonly messages: readonly AwikiSummarySourceMessage[];\n    readonly signal?: AbortSignal;\n}"
          },
          {
            "name": "AwikiSummaryProviderResult",
            "declaration": "export interface AwikiSummaryProviderResult {\n    readonly highlights: readonly string[];\n    readonly conclusions: readonly string[];\n    readonly todos: readonly AwikiSummaryTodo[];\n}"
          },
          {
            "name": "AwikiSummaryRange",
            "declaration": "export interface AwikiSummaryRange {\n    readonly kind: 'unread' | 'recent';\n    readonly messageCount: number;\n    readonly firstMessageId: AwikiMessageId;\n    readonly lastMessageId: AwikiMessageId;\n    readonly startedAt: number;\n    readonly endedAt: number;\n    readonly truncated: boolean;\n}"
          },
          {
            "name": "AwikiSummarySourceMessage",
            "declaration": "export type AwikiSummarySourceMessage = AwikiSummaryTextMessage | AwikiSummaryAttachmentMessage;"
          },
          {
            "name": "AwikiSummaryTextMessage",
            "declaration": "export interface AwikiSummaryTextMessage {\n    readonly id: AwikiMessageId;\n    readonly sender: string;\n    readonly outgoing: boolean;\n    readonly sentAt: string;\n    readonly content: { readonly kind: 'text'; readonly text: string; };\n}"
          },
          {
            "name": "AwikiSummaryTodo",
            "declaration": "export interface AwikiSummaryTodo {\n    readonly text: string;\n    readonly owner?: string;\n}"
          },
          {
            "name": "AwikiTextContent",
            "declaration": "export interface AwikiTextContent {\n    readonly kind: 'text';\n    readonly text: string;\n}"
          },
          {
            "name": "AwikiUpdateDisplayNameRequest",
            "declaration": "export interface AwikiUpdateDisplayNameRequest {\n    readonly displayName: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
