/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _awiki_dsh_plugin_awiki_clearLocalData_parameter_0$schema = z.object({
  'confirmation': z.string().readonly(),
})
const _awiki_dsh_plugin_awiki_clearLocalData_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'cleared': z.boolean().readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_createGroup_parameter_0$schema = z.object({
  'name': z.string().readonly(),
  'members': z.array(z.string()).readonly(),
})
const _awiki_dsh_plugin_awiki_createGroup_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'conversation': z.object({
  'kind': z.literal("group").readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'groupDid': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'unreadCount': z.number().readonly().optional(),
  'lastMessageAt': z.number().readonly().optional(),
  'lastMessagePreview': z.string().readonly().optional(),
}).readonly(),
  'addedMembers': z.array(z.object({
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'handle': z.intersection(z.string(), z.unknown()).readonly().optional(),
})).readonly(),
  'failedMembers': z.array(z.object({
  'member': z.string().readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})).readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_downloadAttachment_parameter_0$schema = z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()).readonly(),
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _awiki_dsh_plugin_awiki_downloadAttachment_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'attachment': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'size': z.number().readonly(),
  'sha256': z.string().readonly(),
}).readonly(),
  'bytesBase64': z.string().readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_getConfig_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'pollIntervalMs': z.number().readonly(),
  'attachmentMaxBytes': z.number().readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_getHistory_parameter_0$schema = z.object({
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'cursor': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'limit': z.number().readonly().optional(),
})
const _awiki_dsh_plugin_awiki_getHistory_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationKind': z.union([z.literal("group"), z.literal("direct")]).readonly(),
  'senderDid': z.intersection(z.string(), z.unknown()).readonly(),
  'senderHandle': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'senderDisplayName': z.string().readonly().optional(),
  'sentAt': z.number().readonly(),
  'outgoing': z.boolean().readonly(),
  'content': z.union([z.object({
  'kind': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'kind': z.literal("attachment").readonly(),
  'attachment': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'size': z.number().readonly(),
  'sha256': z.string().readonly(),
}).readonly(),
  'caption': z.string().readonly().optional(),
})]).readonly(),
})).readonly(),
  'nextCursor': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'hasMore': z.boolean().readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_getLocalHistory_parameter_0$schema = _awiki_dsh_plugin_awiki_getHistory_parameter_0$schema
const _awiki_dsh_plugin_awiki_getLocalHistory_result$schema = _awiki_dsh_plugin_awiki_getHistory_result$schema
const _awiki_dsh_plugin_awiki_getIdentity_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.literal(null), z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.string().readonly().optional(),
  'registeredAt': z.number().readonly(),
})]).readonly(),
})])
const _awiki_dsh_plugin_awiki_getSession_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.object({
  'status': z.literal("unregistered").readonly(),
}), z.object({
  'status': z.literal("signed-out").readonly(),
}), z.object({
  'status': z.literal("active").readonly(),
  'identity': z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.string().readonly().optional(),
  'registeredAt': z.number().readonly(),
}).readonly(),
})]).readonly(),
})])
const _awiki_dsh_plugin_awiki_listConversations_parameter_0$schema = z.union([z.undefined(), z.object({
  'cursor': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'limit': z.number().readonly().optional(),
})])
const _awiki_dsh_plugin_awiki_listConversations_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.union([z.object({
  'kind': z.literal("group").readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'groupDid': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'unreadCount': z.number().readonly().optional(),
  'lastMessageAt': z.number().readonly().optional(),
  'lastMessagePreview': z.string().readonly().optional(),
}), z.object({
  'kind': z.literal("direct").readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'peerDid': z.intersection(z.string(), z.unknown()).readonly(),
  'peerHandle': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'displayName': z.string().readonly().optional(),
  'title': z.string().readonly(),
  'unreadCount': z.number().readonly().optional(),
  'lastMessageAt': z.number().readonly().optional(),
  'lastMessagePreview': z.string().readonly().optional(),
})])).readonly(),
  'nextCursor': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'hasMore': z.boolean().readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_login_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.object({
  'status': z.literal("unregistered").readonly(),
}), z.object({
  'status': z.literal("signed-out").readonly(),
}), z.object({
  'status': z.literal("active").readonly(),
  'identity': z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.string().readonly().optional(),
  'registeredAt': z.number().readonly(),
}).readonly(),
})]).readonly(),
})])
const _awiki_dsh_plugin_awiki_logout_parameter_0$schema = z.object({
  'confirmation': z.string().readonly(),
})
const _awiki_dsh_plugin_awiki_logout_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.object({
  'status': z.literal("unregistered").readonly(),
}), z.object({
  'status': z.literal("signed-out").readonly(),
}), z.object({
  'status': z.literal("active").readonly(),
  'identity': z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.string().readonly().optional(),
  'registeredAt': z.number().readonly(),
}).readonly(),
})]).readonly(),
})])
const _awiki_dsh_plugin_awiki_markConversationRead_parameter_0$schema = z.object({
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _awiki_dsh_plugin_awiki_markConversationRead_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.number().readonly(),
})])
const _awiki_dsh_plugin_awiki_registerIdentity_parameter_0$schema = z.object({
  'handle': z.string().readonly(),
  'phone': z.string().readonly(),
  'otp': z.string().readonly(),
})
const _awiki_dsh_plugin_awiki_registerIdentity_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.string().readonly().optional(),
  'registeredAt': z.number().readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_resolvePeer_parameter_0$schema = z.object({
  'peer': z.string().readonly(),
})
const _awiki_dsh_plugin_awiki_resolvePeer_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'handle': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'displayName': z.string().readonly().optional(),
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_sendAttachment_parameter_0$schema = z.object({
  'target': z.union([z.object({
  'kind': z.literal("direct").readonly(),
  'peer': z.string().readonly(),
}), z.object({
  'kind': z.literal("group").readonly(),
  'group': z.string().readonly(),
})]).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'bytesBase64': z.string().readonly(),
  'caption': z.string().readonly().optional(),
  'idempotencyKey': z.string().readonly(),
})
const _awiki_dsh_plugin_awiki_sendAttachment_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationKind': z.union([z.literal("group"), z.literal("direct")]).readonly(),
  'senderDid': z.intersection(z.string(), z.unknown()).readonly(),
  'senderHandle': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'senderDisplayName': z.string().readonly().optional(),
  'sentAt': z.number().readonly(),
  'outgoing': z.boolean().readonly(),
  'content': z.union([z.object({
  'kind': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'kind': z.literal("attachment").readonly(),
  'attachment': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'size': z.number().readonly(),
  'sha256': z.string().readonly(),
}).readonly(),
  'caption': z.string().readonly().optional(),
})]).readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_sendRegistrationOtp_parameter_0$schema = z.object({
  'handle': z.string().readonly(),
  'phone': z.string().readonly(),
})
const _awiki_dsh_plugin_awiki_sendRegistrationOtp_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'retryAfterSeconds': z.number().readonly(),
  'retryAt': z.string().readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_sendText_parameter_0$schema = z.object({
  'target': z.union([z.object({
  'kind': z.literal("direct").readonly(),
  'peer': z.string().readonly(),
}), z.object({
  'kind': z.literal("group").readonly(),
  'group': z.string().readonly(),
})]).readonly(),
  'text': z.string().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _awiki_dsh_plugin_awiki_sendText_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'conversationKind': z.union([z.literal("group"), z.literal("direct")]).readonly(),
  'senderDid': z.intersection(z.string(), z.unknown()).readonly(),
  'senderHandle': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'senderDisplayName': z.string().readonly().optional(),
  'sentAt': z.number().readonly(),
  'outgoing': z.boolean().readonly(),
  'content': z.union([z.object({
  'kind': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'kind': z.literal("attachment").readonly(),
  'attachment': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'fileName': z.string().readonly(),
  'mimeType': z.string().readonly(),
  'size': z.number().readonly(),
  'sha256': z.string().readonly(),
}).readonly(),
  'caption': z.string().readonly().optional(),
})]).readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_summarizeConversation_parameter_0$schema = z.object({
  'conversationId': z.intersection(z.string(), z.unknown()).readonly(),
  'unreadCountAtOpen': z.number().readonly().optional(),
})
const _awiki_dsh_plugin_awiki_summarizeConversation_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'range': z.object({
  'kind': z.union([z.literal("unread"), z.literal("recent")]).readonly(),
  'messageCount': z.number().readonly(),
  'firstMessageId': z.intersection(z.string(), z.unknown()).readonly(),
  'lastMessageId': z.intersection(z.string(), z.unknown()).readonly(),
  'startedAt': z.number().readonly(),
  'endedAt': z.number().readonly(),
  'truncated': z.boolean().readonly(),
}).readonly(),
  'highlights': z.array(z.string()).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'todos': z.array(z.object({
  'text': z.string().readonly(),
  'owner': z.string().readonly().optional(),
})).readonly(),
}).readonly(),
})])
const _awiki_dsh_plugin_awiki_updateDisplayName_parameter_0$schema = z.object({
  'displayName': z.string().readonly(),
})
const _awiki_dsh_plugin_awiki_updateDisplayName_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("not-registered"), z.literal("signed-out"), z.literal("already-registered"), z.literal("invalid-request"), z.literal("invalid-otp"), z.literal("challenge-expired"), z.literal("handle-unavailable"), z.literal("not-found"), z.literal("forbidden"), z.literal("conflict"), z.literal("rate-limited"), z.literal("attachment-too-large"), z.literal("summary-unavailable"), z.literal("summary-timeout"), z.literal("summary-cancelled"), z.literal("summary-invalid-output"), z.literal("summary-failed"), z.literal("network"), z.literal("remote")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'handle': z.intersection(z.string(), z.unknown()).readonly(),
  'did': z.intersection(z.string(), z.unknown()).readonly(),
  'displayName': z.string().readonly().optional(),
  'registeredAt': z.number().readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: '@awiki/dsh-plugin',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@awiki/dsh-plugin#awiki/clearLocalData',
      service: 'awiki',
      namespace: 'awiki',
      method: 'clearLocalData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiClearLocalDataRequest',
            schema: _awiki_dsh_plugin_awiki_clearLocalData_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_clearLocalData_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":897,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/createGroup',
      service: 'awiki',
      namespace: 'awiki',
      method: 'createGroup',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiCreateGroupRequest',
            schema: _awiki_dsh_plugin_awiki_createGroup_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_createGroup_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":707,"column":9},
    },
    {
      id: '@awiki/dsh-plugin#awiki/downloadAttachment',
      service: 'awiki',
      namespace: 'awiki',
      method: 'downloadAttachment',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiDownloadAttachmentRequest',
            schema: _awiki_dsh_plugin_awiki_downloadAttachment_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_downloadAttachment_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":878,"column":9},
    },
    {
      id: '@awiki/dsh-plugin#awiki/getConfig',
      service: 'awiki',
      namespace: 'awiki',
      method: 'getConfig',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_getConfig_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":591,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/getHistory',
      service: 'awiki',
      namespace: 'awiki',
      method: 'getHistory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiHistoryRequest',
            schema: _awiki_dsh_plugin_awiki_getHistory_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_getHistory_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":741,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/getLocalHistory',
      service: 'awiki',
      namespace: 'awiki',
      method: 'getLocalHistory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiHistoryRequest',
            schema: _awiki_dsh_plugin_awiki_getLocalHistory_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_getLocalHistory_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":756,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/getIdentity',
      service: 'awiki',
      namespace: 'awiki',
      method: 'getIdentity',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_getIdentity_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":606,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/getSession',
      service: 'awiki',
      namespace: 'awiki',
      method: 'getSession',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_getSession_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":612,"column":9},
    },
    {
      id: '@awiki/dsh-plugin#awiki/listConversations',
      service: 'awiki',
      namespace: 'awiki',
      method: 'listConversations',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiPageRequest',
            schema: _awiki_dsh_plugin_awiki_listConversations_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_listConversations_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":731,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/login',
      service: 'awiki',
      namespace: 'awiki',
      method: 'login',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_login_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":645,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/logout',
      service: 'awiki',
      namespace: 'awiki',
      method: 'logout',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiLogoutRequest',
            schema: _awiki_dsh_plugin_awiki_logout_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_logout_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":623,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/markConversationRead',
      service: 'awiki',
      namespace: 'awiki',
      method: 'markConversationRead',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiMarkConversationReadRequest',
            schema: _awiki_dsh_plugin_awiki_markConversationRead_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_markConversationRead_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":837,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/registerIdentity',
      service: 'awiki',
      namespace: 'awiki',
      method: 'registerIdentity',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiRegistrationRequest',
            schema: _awiki_dsh_plugin_awiki_registerIdentity_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_registerIdentity_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":677,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/resolvePeer',
      service: 'awiki',
      namespace: 'awiki',
      method: 'resolvePeer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiResolvePeerRequest',
            schema: _awiki_dsh_plugin_awiki_resolvePeer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_resolvePeer_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":697,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/sendAttachment',
      service: 'awiki',
      namespace: 'awiki',
      method: 'sendAttachment',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiSendAttachmentRequest',
            schema: _awiki_dsh_plugin_awiki_sendAttachment_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_sendAttachment_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":857,"column":9},
    },
    {
      id: '@awiki/dsh-plugin#awiki/sendRegistrationOtp',
      service: 'awiki',
      namespace: 'awiki',
      method: 'sendRegistrationOtp',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiRegistrationOtpRequest',
            schema: _awiki_dsh_plugin_awiki_sendRegistrationOtp_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_sendRegistrationOtp_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":667,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/sendText',
      service: 'awiki',
      namespace: 'awiki',
      method: 'sendText',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiSendTextRequest',
            schema: _awiki_dsh_plugin_awiki_sendText_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_sendText_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":847,"column":3},
    },
    {
      id: '@awiki/dsh-plugin#awiki/summarizeConversation',
      service: 'awiki',
      namespace: 'awiki',
      method: 'summarizeConversation',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiSummarizeConversationRequest',
            schema: _awiki_dsh_plugin_awiki_summarizeConversation_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_summarizeConversation_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":751,"column":9},
    },
    {
      id: '@awiki/dsh-plugin#awiki/updateDisplayName',
      service: 'awiki',
      namespace: 'awiki',
      method: 'updateDisplayName',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@awiki/dsh-plugin/types#AwikiUpdateDisplayNameRequest',
            schema: _awiki_dsh_plugin_awiki_updateDisplayName_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@awiki/dsh-plugin/types#AwikiResult',
        schema: _awiki_dsh_plugin_awiki_updateDisplayName_result$schema,
      },
      sourceLocation: {"file":"packages/awiki/awiki/src/index.ts","line":687,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Deployment-wide AWiki service over one replaceable high-level client provider.",
        "summary": "Deployment-wide AWiki service over one replaceable high-level client provider.",
        "tags": [],
        "jsDoc": "/** Deployment-wide AWiki service over one replaceable high-level client provider. */",
        "key": "awiki",
        "exportName": "AwikiService",
        "members": [
          {
            "kind": "property",
            "name": "externalHttpAuth",
            "signature": "readonly externalHttpAuth: AwikiExternalHttpAuth",
            "summary": "Trusted same-process external HTTP authentication dispatcher.",
            "jsDoc": "/** Trusted same-process external HTTP authentication dispatcher. Never Remote. */"
          },
          {
            "kind": "method",
            "name": "registerClientFactory",
            "signature": "registerClientFactory(factory: AwikiClientFactory): () => Promise<void>",
            "summary": "Register the deployment's sole client factory.",
            "jsDoc": "/**\n * Register the deployment's sole client factory. The caller must return the\n * resulting disposer from its own `ctx.effect`; disposal clears the slot\n * before awaiting the client's quiescence and is idempotent.\n * @param factory - synchronous factory for one owned high-level client.\n * @returns asynchronous disposer for the exact registered client.\n */"
          },
          {
            "kind": "method",
            "name": "registerSummaryProvider",
            "signature": "registerSummaryProvider(provider: AwikiSummaryProvider): () => void",
            "summary": "Register one replaceable conversation-summary provider for this deployment.",
            "jsDoc": "/** Register one replaceable conversation-summary provider for this deployment. */"
          },
          {
            "kind": "method",
            "name": "getConfig",
            "signature": "@Remote getConfig(): Promise<AwikiResult<AwikiRuntimeConfig>>",
            "summary": "Read settings needed by the browser presentation.",
            "jsDoc": "/**\n * Read settings needed by the browser presentation.\n * @returns Browser-safe polling configuration without SDK endpoints or state paths.\n */"
          },
          {
            "kind": "method",
            "name": "getIdentity",
            "signature": "@Remote getIdentity(): Promise<AwikiResult<AwikiIdentity | null>>",
            "summary": "Read the deployment's identity status.",
            "jsDoc": "/**\n * Read the deployment's identity status.\n * @returns The public deployment identity or `null`.\n */"
          },
          {
            "kind": "method",
            "name": "getSession",
            "signature": "@Remote async getSession(): Promise<AwikiResult<AwikiSession>>",
            "summary": "Return the local registration and sign-in state without exposing secrets.",
            "jsDoc": "/** Return the local registration and sign-in state without exposing secrets. */"
          },
          {
            "kind": "method",
            "name": "logout",
            "signature": "@Remote logout(request: AwikiLogoutRequest): Promise<AwikiResult<AwikiSession>>",
            "summary": "Lock this installation while preserving the encrypted identity and local database.",
            "jsDoc": "/** Lock this installation while preserving the encrypted identity and local database. */"
          },
          {
            "kind": "method",
            "name": "login",
            "signature": "@Remote login(): Promise<AwikiResult<AwikiSession>>",
            "summary": "Resume the same locally preserved identity without registration.",
            "jsDoc": "/** Resume the same locally preserved identity without registration. */"
          },
          {
            "kind": "method",
            "name": "sendRegistrationOtp",
            "signature": "@Remote sendRegistrationOtp(request: AwikiRegistrationOtpRequest): Promise<AwikiResult<AwikiRegistrationOtpResult>>",
            "summary": "Send one Legacy registration verification code.",
            "jsDoc": "/**\n * Send one Legacy registration verification code.\n * @param request - Handle and phone used for the registration challenge.\n * @returns Public retry timing or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "registerIdentity",
            "signature": "@Remote registerIdentity(request: AwikiRegistrationRequest): Promise<AwikiResult<AwikiIdentity>>",
            "summary": "Register and persist the deployment's only AWiki identity.",
            "jsDoc": "/**\n * Register and persist the deployment's only AWiki identity.\n * @param request - Handle, phone, and verification code for registration.\n * @returns The new public identity or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "updateDisplayName",
            "signature": "@Remote updateDisplayName(request: AwikiUpdateDisplayNameRequest): Promise<AwikiResult<AwikiIdentity>>",
            "summary": "Update the deployment identity's public WNS display name.",
            "jsDoc": "/**\n * Update the deployment identity's public WNS display name.\n * @param request - replacement display name selected by the user.\n * @returns The updated public identity or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "resolvePeer",
            "signature": "@Remote resolvePeer(request: AwikiResolvePeerRequest): Promise<AwikiResult<AwikiResolvedPeer>>",
            "summary": "Resolve one Handle or DID before the browser opens a direct chat.",
            "jsDoc": "/**\n * Resolve one Handle or DID before the browser opens a direct chat.\n * @param request - typed Handle or DID.\n * @returns The public peer and conversation id, or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "createGroup",
            "signature": "@Remote async createGroup(request: AwikiCreateGroupRequest): Promise<AwikiResult<AwikiCreateGroupResult>>",
            "summary": "Create one group, then settle every initial-member invitation without hiding a created group.",
            "jsDoc": "/**\n * Create one group, then settle every initial-member invitation without hiding a created group.\n * @param request - bounded group name and initial Handle/DID values.\n * @returns The created conversation and per-member outcomes.\n */"
          },
          {
            "kind": "method",
            "name": "listConversations",
            "signature": "@Remote listConversations(request?: AwikiPageRequest): Promise<AwikiResult<AwikiPage<AwikiConversation>>>",
            "summary": "List direct and existing group conversations.",
            "jsDoc": "/**\n * List direct and existing group conversations.\n * @param request - Optional opaque cursor and page limit.\n * @returns One page of direct and existing group conversations.\n */"
          },
          {
            "kind": "method",
            "name": "getHistory",
            "signature": "@Remote getHistory(request: AwikiHistoryRequest): Promise<AwikiResult<AwikiPage<AwikiMessage>>>",
            "summary": "Read one direct or group conversation history page.",
            "jsDoc": "/**\n * Read one direct or group conversation history page.\n * @param request - Conversation id, optional cursor, and page limit.\n * @returns One chronological history page.\n */"
          },
          {
            "kind": "method",
            "name": "summarizeConversation",
            "signature": "@Remote async summarizeConversation( request: AwikiSummarizeConversationRequest, ): Promise<AwikiResult<AwikiConversationSummary>>",
            "summary": "Read real AWiki history, enforce range and byte caps, then invoke the configured model once.",
            "jsDoc": "/**\n * Read real AWiki history, enforce range and byte caps, then invoke the configured model once.\n * @param request - selected conversation and its unread snapshot at open time.\n * @returns a structured summary plus the exact summarized source range.\n */"
          },
          {
            "kind": "method",
            "name": "markConversationRead",
            "signature": "@Remote markConversationRead(request: AwikiMarkConversationReadRequest): Promise<AwikiResult<number>>",
            "summary": "Mark every currently unread inbox message in one conversation as read.",
            "jsDoc": "/**\n * Mark every currently unread inbox message in one conversation as read.\n * @param request - conversation whose current inbox entries should be acknowledged.\n * @returns Number of inbox entries acknowledged by the Message Service.\n */"
          },
          {
            "kind": "method",
            "name": "sendText",
            "signature": "@Remote sendText(request: AwikiSendTextRequest): Promise<AwikiResult<AwikiMessage>>",
            "summary": "Send one text message through the deployment identity.",
            "jsDoc": "/**\n * Send one text message through the deployment identity.\n * @param request - Target, text, and idempotency key.\n * @returns The accepted public message or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "sendAttachment",
            "signature": "@Remote async sendAttachment(request: AwikiSendAttachmentRequest): Promise<AwikiResult<AwikiMessage>>",
            "summary": "Upload and send one attachment after Host validation.",
            "jsDoc": "/**\n * Upload and send one attachment after Host validation.\n * @param request - Target, attachment metadata and Base64 bytes, caption, and idempotency key.\n * @returns The accepted attachment message or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "downloadAttachment",
            "signature": "@Remote async downloadAttachment(request: AwikiDownloadAttachmentRequest): Promise<AwikiResult<AwikiDownloadedAttachment>>",
            "summary": "Download and encode one provider-verified attachment.",
            "jsDoc": "/**\n * Download and encode one provider-verified attachment.\n * @param request - Containing message id and attachment id.\n * @returns Verified public metadata and canonical Base64 bytes, or a closed failure.\n */"
          },
          {
            "kind": "method",
            "name": "clearLocalData",
            "signature": "@Remote clearLocalData(request: AwikiClearLocalDataRequest): Promise<AwikiResult<AwikiClearLocalDataResult>>",
            "summary": "Permanently remove the exact SDK-owned local state after an explicit browser acknowledgement.",
            "jsDoc": "/**\n * Permanently remove the exact SDK-owned local state after an explicit browser acknowledgement.\n * The remote AWiki account and Handle are not deleted.\n * @param request - exact destructive-action marker emitted only after the UI's second confirmation.\n * @returns Whether a persisted state file existed when the reset completed.\n */"
          }
        ],
        "types": [
          {
            "name": "AwikiAttachment",
            "declaration": "export interface AwikiAttachment {\n    readonly id: AwikiAttachmentId;\n    readonly fileName: string;\n    readonly mimeType: string;\n    readonly size: number;\n    readonly sha256: string;\n}"
          },
          {
            "name": "AwikiAttachmentContent",
            "declaration": "export interface AwikiAttachmentContent {\n    readonly kind: 'attachment';\n    readonly attachment: AwikiAttachment;\n    readonly caption?: string;\n}"
          },
          {
            "name": "AwikiAttachmentId",
            "declaration": "export type AwikiAttachmentId = Branded<'AwikiAttachmentId'>;"
          },
          {
            "name": "AwikiClearLocalDataRequest",
            "declaration": "export interface AwikiClearLocalDataRequest {\n    readonly confirmation: string;\n}"
          },
          {
            "name": "AwikiClearLocalDataResult",
            "declaration": "export interface AwikiClearLocalDataResult {\n    readonly cleared: boolean;\n}"
          },
          {
            "name": "AwikiClientFactory",
            "declaration": "export type AwikiClientFactory = (options: AwikiClientOptions) => AwikiSdkClient;"
          },
          {
            "name": "AwikiClientOptions",
            "declaration": "export interface AwikiClientOptions {\n    readonly userServiceUrl: string;\n    readonly userServiceDomain: string;\n    readonly messageServiceUrl: string;\n    readonly messageServicePublicUrl: string;\n    readonly messageServiceDid: string;\n    readonly allowedAttachmentOrigins: readonly string[];\n    readonly attachmentMaxBytes: number;\n    readonly allowInsecureLoopbackForTesting: boolean;\n    readonly stateRoot: string;\n}"
          },
          {
            "name": "AwikiConversation",
            "declaration": "export type AwikiConversation = AwikiDirectConversation | AwikiGroupConversation;"
          },
          {
            "name": "AwikiConversationId",
            "declaration": "export type AwikiConversationId = Branded<'AwikiConversationId'>;"
          },
          {
            "name": "AwikiConversationSummary",
            "declaration": "export interface AwikiConversationSummary {\n    readonly range: AwikiSummaryRange;\n    readonly highlights: readonly string[];\n    readonly conclusions: readonly string[];\n    readonly todos: readonly AwikiSummaryTodo[];\n}"
          },
          {
            "name": "AwikiCreateGroupRequest",
            "declaration": "export interface AwikiCreateGroupRequest {\n    readonly name: string;\n    readonly members: readonly string[];\n}"
          },
          {
            "name": "AwikiCreateGroupResult",
            "declaration": "export interface AwikiCreateGroupResult {\n    readonly conversation: AwikiGroupConversation;\n    readonly addedMembers: readonly AwikiGroupMember[];\n    readonly failedMembers: readonly AwikiGroupMemberFailure[];\n}"
          },
          {
            "name": "AwikiCursor",
            "declaration": "export type AwikiCursor = Branded<'AwikiCursor'>;"
          },
          {
            "name": "AwikiDid",
            "declaration": "export type AwikiDid = Branded<'AwikiDid'>;"
          },
          {
            "name": "AwikiDirectConversation",
            "declaration": "export interface AwikiDirectConversation {\n    readonly kind: 'direct';\n    readonly id: AwikiConversationId;\n    readonly peerDid: AwikiDid;\n    readonly peerHandle?: AwikiHandle;\n    readonly displayName?: string;\n    readonly title: string;\n    readonly unreadCount?: number;\n    readonly lastMessageAt?: number;\n    readonly lastMessagePreview?: string;\n}"
          },
          {
            "name": "AwikiDirectTarget",
            "declaration": "export interface AwikiDirectTarget {\n    readonly kind: 'direct';\n    readonly peer: string;\n}"
          },
          {
            "name": "AwikiDownloadAttachmentRequest",
            "declaration": "export interface AwikiDownloadAttachmentRequest {\n    readonly attachmentId: AwikiAttachmentId;\n    readonly messageId: AwikiMessageId;\n}"
          },
          {
            "name": "AwikiDownloadedAttachment",
            "declaration": "export interface AwikiDownloadedAttachment {\n    readonly attachment: AwikiAttachment;\n    readonly bytesBase64: string;\n}"
          },
          {
            "name": "AwikiExternalHttpAuth",
            "declaration": "export interface AwikiExternalHttpAuth {\n    dispatch(request: Request, transport: AwikiHttpTransport): Promise<Response>;\n}"
          },
          {
            "name": "AwikiFailure",
            "declaration": "export interface AwikiFailure {\n    readonly code: AwikiFailureCode;\n    readonly message: string;\n}"
          },
          {
            "name": "AwikiFailureCode",
            "declaration": "export type AwikiFailureCode = 'not-registered' | 'signed-out' | 'already-registered' | 'invalid-request' | 'invalid-otp' | 'challenge-expired' | 'handle-unavailable' | 'not-found' | 'forbidden' | 'conflict' | 'rate-limited' | 'attachment-too-large' | 'summary-unavailable' | 'summary-timeout' | 'summary-cancelled' | 'summary-invalid-output' | 'summary-failed' | 'network' | 'remote';"
          },
          {
            "name": "AwikiGroupConversation",
            "declaration": "export interface AwikiGroupConversation {\n    readonly kind: 'group';\n    readonly id: AwikiConversationId;\n    readonly groupDid: AwikiDid;\n    readonly title: string;\n    readonly unreadCount?: number;\n    readonly lastMessageAt?: number;\n    readonly lastMessagePreview?: string;\n}"
          },
          {
            "name": "AwikiGroupMember",
            "declaration": "export interface AwikiGroupMember {\n    readonly did: AwikiDid;\n    readonly handle?: AwikiHandle;\n}"
          },
          {
            "name": "AwikiGroupMemberFailure",
            "declaration": "export interface AwikiGroupMemberFailure {\n    readonly member: string;\n    readonly error: AwikiFailure;\n}"
          },
          {
            "name": "AwikiGroupTarget",
            "declaration": "export interface AwikiGroupTarget {\n    readonly kind: 'group';\n    readonly group: string;\n}"
          },
          {
            "name": "AwikiHandle",
            "declaration": "export type AwikiHandle = Branded<'AwikiHandle'>;"
          },
          {
            "name": "AwikiHistoryRequest",
            "declaration": "export interface AwikiHistoryRequest extends AwikiPageRequest {\n    readonly conversationId: AwikiConversationId;\n}"
          },
          {
            "name": "AwikiHttpTransport",
            "declaration": "export type AwikiHttpTransport = (request: Request) => Promise<Response>;"
          },
          {
            "name": "AwikiIdentity",
            "declaration": "export interface AwikiIdentity {\n    readonly handle: AwikiHandle;\n    readonly did: AwikiDid;\n    readonly displayName?: string;\n    readonly registeredAt: number;\n}"
          },
          {
            "name": "AwikiLogoutRequest",
            "declaration": "export interface AwikiLogoutRequest {\n    readonly confirmation: string;\n}"
          },
          {
            "name": "AwikiMarkConversationReadRequest",
            "declaration": "export interface AwikiMarkConversationReadRequest {\n    readonly conversationId: AwikiConversationId;\n}"
          },
          {
            "name": "AwikiMessage",
            "declaration": "export interface AwikiMessage {\n    readonly id: AwikiMessageId;\n    readonly conversationId: AwikiConversationId;\n    readonly conversationKind: AwikiConversation['kind'];\n    readonly senderDid: AwikiDid;\n    readonly senderHandle?: AwikiHandle;\n    readonly senderDisplayName?: string;\n    readonly sentAt: number;\n    readonly outgoing: boolean;\n    readonly content: AwikiMessageContent;\n}"
          },
          {
            "name": "AwikiMessageContent",
            "declaration": "export type AwikiMessageContent = AwikiTextContent | AwikiAttachmentContent;"
          },
          {
            "name": "AwikiMessageId",
            "declaration": "export type AwikiMessageId = Branded<'AwikiMessageId'>;"
          },
          {
            "name": "AwikiMessageTarget",
            "declaration": "export type AwikiMessageTarget = AwikiDirectTarget | AwikiGroupTarget;"
          },
          {
            "name": "AwikiPage",
            "declaration": "export interface AwikiPage<Item> {\n    readonly items: readonly Item[];\n    readonly nextCursor?: AwikiCursor;\n    readonly hasMore: boolean;\n}"
          },
          {
            "name": "AwikiPageRequest",
            "declaration": "export interface AwikiPageRequest {\n    readonly cursor?: AwikiCursor;\n    readonly limit?: number;\n}"
          },
          {
            "name": "AwikiRegistrationOtpRequest",
            "declaration": "export interface AwikiRegistrationOtpRequest {\n    readonly handle: string;\n    readonly phone: string;\n}"
          },
          {
            "name": "AwikiRegistrationOtpResult",
            "declaration": "export interface AwikiRegistrationOtpResult {\n    readonly retryAfterSeconds: number;\n    readonly retryAt: string;\n}"
          },
          {
            "name": "AwikiRegistrationRequest",
            "declaration": "export interface AwikiRegistrationRequest {\n    readonly handle: string;\n    readonly phone: string;\n    readonly otp: string;\n}"
          },
          {
            "name": "AwikiRejected",
            "declaration": "export interface AwikiRejected {\n    readonly ok: false;\n    readonly error: AwikiFailure;\n}"
          },
          {
            "name": "AwikiResolvedPeer",
            "declaration": "export interface AwikiResolvedPeer {\n    readonly did: AwikiDid;\n    readonly handle?: AwikiHandle;\n    readonly displayName?: string;\n    readonly conversationId: AwikiConversationId;\n}"
          },
          {
            "name": "AwikiResolvePeerRequest",
            "declaration": "export interface AwikiResolvePeerRequest {\n    readonly peer: string;\n}"
          },
          {
            "name": "AwikiResult",
            "declaration": "export type AwikiResult<Value> = AwikiSuccess<Value> | AwikiRejected;"
          },
          {
            "name": "AwikiRuntimeConfig",
            "declaration": "export interface AwikiRuntimeConfig {\n    readonly pollIntervalMs: number;\n    readonly attachmentMaxBytes: number;\n}"
          },
          {
            "name": "AwikiSdkAttachmentUpload",
            "declaration": "export interface AwikiSdkAttachmentUpload {\n    readonly fileName: string;\n    readonly mimeType: string;\n    readonly bytes: Uint8Array;\n}"
          },
          {
            "name": "AwikiSdkClient",
            "declaration": "export interface AwikiSdkClient {\n    prepareExternalHttpRequest(request: AwikiSdkExternalHttpRequest): Promise<AwikiSdkExternalHttpAttempt>;\n    getIdentity(): Promise<AwikiIdentity | null>;\n    sendRegistrationOtp(request: AwikiRegistrationOtpRequest): Promise<AwikiRegistrationOtpResult>;\n    registerIdentity(request: AwikiRegistrationRequest): Promise<AwikiIdentity>;\n    updateDisplayName(request: AwikiUpdateDisplayNameRequest): Promise<AwikiIdentity>;\n    resolvePeer(peer: string): Promise<AwikiResolvedPeer>;\n    createGroup(name: string): Promise<AwikiGroupConversation>;\n    addGroupMember(groupDid: AwikiDid, member: string): Promise<AwikiGroupMember>;\n    listConversations(request?: AwikiPageRequest): Promise<AwikiPage<AwikiConversation>>;\n    getHistory(request: AwikiHistoryRequest): Promise<AwikiPage<AwikiMessage>>;\n    markConversationRead(conversationId: AwikiConversationId): Promise<number>;\n    sendText(request: AwikiSendTextRequest): Promise<AwikiMessage>;\n    sendAttachment(request: AwikiSdkSendAttachmentRequest): Promise<AwikiMessage>;\n    downloadAttachment(request: { readonly attachmentId: AwikiAttachmentId; readonly messageId: AwikiMessageId; }): Promise<AwikiSdkDownloadedAttachment>;\n    clearLocalData(): Promise<{ readonly cleared: boolean; }>;\n    dispose(): Promise<void>;\n}"
          },
          {
            "name": "AwikiSdkDownloadedAttachment",
            "declaration": "export interface AwikiSdkDownloadedAttachment {\n    readonly attachment: AwikiAttachment;\n    readonly bytes: Uint8Array;\n}"
          },
          {
            "name": "AwikiSdkExternalHttpAttempt",
            "declaration": "export interface AwikiSdkExternalHttpAttempt {\n    readonly targetUrl: string;\n    readonly method: string;\n    readonly headerPatch: readonly AwikiSdkHttpHeader[];\n    readonly retryCount: number;\n    handleResponse(response: AwikiSdkExternalHttpResponse): Promise<AwikiSdkExternalHttpAttempt | null>;\n}"
          },
          {
            "name": "AwikiSdkExternalHttpRequest",
            "declaration": "export interface AwikiSdkExternalHttpRequest {\n    readonly url: string;\n    readonly method: string;\n    readonly headers: readonly AwikiSdkHttpHeader[];\n    readonly body?: Uint8Array;\n}"
          },
          {
            "name": "AwikiSdkExternalHttpResponse",
            "declaration": "export interface AwikiSdkExternalHttpResponse {\n    readonly statusCode: number;\n    readonly headers: readonly AwikiSdkHttpHeader[];\n}"
          },
          {
            "name": "AwikiSdkHttpHeader",
            "declaration": "export interface AwikiSdkHttpHeader {\n    readonly name: string;\n    readonly value: string;\n}"
          },
          {
            "name": "AwikiSdkSendAttachmentRequest",
            "declaration": "export interface AwikiSdkSendAttachmentRequest {\n    readonly target: AwikiMessageTarget;\n    readonly attachment: AwikiSdkAttachmentUpload;\n    readonly caption?: string;\n    readonly idempotencyKey: string;\n}"
          },
          {
            "name": "AwikiSendAttachmentRequest",
            "declaration": "export interface AwikiSendAttachmentRequest {\n    readonly target: AwikiMessageTarget;\n    readonly fileName: string;\n    readonly mimeType: string;\n    readonly bytesBase64: string;\n    readonly caption?: string;\n    readonly idempotencyKey: string;\n}"
          },
          {
            "name": "AwikiSendTextRequest",
            "declaration": "export interface AwikiSendTextRequest {\n    readonly target: AwikiMessageTarget;\n    readonly text: string;\n    readonly idempotencyKey: string;\n}"
          },
          {
            "name": "AwikiSession",
            "declaration": "export type AwikiSession = { readonly status: 'unregistered'; } | { readonly status: 'signed-out'; } | { readonly status: 'active'; readonly identity: AwikiIdentity; };"
          },
          {
            "name": "AwikiSuccess",
            "declaration": "export interface AwikiSuccess<Value> {\n    readonly ok: true;\n    readonly value: Value;\n}"
          },
          {
            "name": "AwikiSummarizeConversationRequest",
            "declaration": "export interface AwikiSummarizeConversationRequest {\n    readonly conversationId: AwikiConversationId;\n    readonly unreadCountAtOpen?: number;\n}"
          },
          {
            "name": "AwikiSummaryAttachmentMessage",
            "declaration": "export interface AwikiSummaryAttachmentMessage {\n    readonly id: AwikiMessageId;\n    readonly sender: string;\n    readonly outgoing: boolean;\n    readonly sentAt: string;\n    readonly content: { readonly kind: 'attachment'; readonly fileName: string; readonly mimeType: string; readonly size: number; readonly caption?: string; };\n}"
          },
          {
            "name": "AwikiSummaryProvider",
            "declaration": "export interface AwikiSummaryProvider {\n    summarize(request: AwikiSummaryProviderRequest): Promise<AwikiSummaryProviderResult>;\n}"
          },
          {
            "name": "AwikiSummaryProviderRequest",
            "declaration": "export interface AwikiSummaryProviderRequest {\n    readonly messages: readonly AwikiSummarySourceMessage[];\n    readonly signal?: AbortSignal;\n}"
          },
          {
            "name": "AwikiSummaryProviderResult",
            "declaration": "export interface AwikiSummaryProviderResult {\n    readonly highlights: readonly string[];\n    readonly conclusions: readonly string[];\n    readonly todos: readonly AwikiSummaryTodo[];\n}"
          },
          {
            "name": "AwikiSummaryRange",
            "declaration": "export interface AwikiSummaryRange {\n    readonly kind: 'unread' | 'recent';\n    readonly messageCount: number;\n    readonly firstMessageId: AwikiMessageId;\n    readonly lastMessageId: AwikiMessageId;\n    readonly startedAt: number;\n    readonly endedAt: number;\n    readonly truncated: boolean;\n}"
          },
          {
            "name": "AwikiSummarySourceMessage",
            "declaration": "export type AwikiSummarySourceMessage = AwikiSummaryTextMessage | AwikiSummaryAttachmentMessage;"
          },
          {
            "name": "AwikiSummaryTextMessage",
            "declaration": "export interface AwikiSummaryTextMessage {\n    readonly id: AwikiMessageId;\n    readonly sender: string;\n    readonly outgoing: boolean;\n    readonly sentAt: string;\n    readonly content: { readonly kind: 'text'; readonly text: string; };\n}"
          },
          {
            "name": "AwikiSummaryTodo",
            "declaration": "export interface AwikiSummaryTodo {\n    readonly text: string;\n    readonly owner?: string;\n}"
          },
          {
            "name": "AwikiTextContent",
            "declaration": "export interface AwikiTextContent {\n    readonly kind: 'text';\n    readonly text: string;\n}"
          },
          {
            "name": "AwikiUpdateDisplayNameRequest",
            "declaration": "export interface AwikiUpdateDisplayNameRequest {\n    readonly displayName: string;\n}"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
